---
title: "1_3_APM_TMB"
author: "AJ"
date: "2025-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library packages
```{r cars}
rm(list = ls())

suppressMessages(library("ggplot2"))
suppressMessages(library("patchwork"))
suppressMessages(library("ggpubr"))
suppressMessages(library("maftools"))
suppressMessages(library("survival"))
suppressMessages(library("survminer"))
suppressMessages(library("tidyr"))
suppressMessages(library("broom"))
suppressMessages(library("data.table"))
suppressMessages(library("dplyr"))
suppressMessages(library("textshape"))
suppressMessages(library("ggrepel"))
suppressMessages(library("tibble"))
suppressMessages(library("readr"))
suppressMessages(library("ggradar"))
suppressMessages(library("ggsci"))
suppressMessages(library("cowplot"))
suppressMessages(library("ggdist"))

color_event <- c("Mut" = "#E64B35FF", "WT" = "#4DBBD5FF")
color_APM_envet <- c("APM-Mutant" = "#E64B35FF", "APM-WT" = "#4DBBD5FF")
figure_path <- ".../Project/Figures/20250813/"
path_tmb <- ".../Project/MHC_evolution/TMB/250813/"
```

# TMB
```{r pressure, echo=FALSE}
path_maf <- ".../Project/consensus_snv_indel/maf/maf_from_vcf/"

mat1 <- fread(paste0(path_maf, "/onco_APM_hlaloh.txt")) %>% 
  column_to_rownames("V1") %>% 
  as.matrix()

long_df <- as.data.frame(mat1) %>%
  rownames_to_column("Gene") %>%
  pivot_longer(-Gene, names_to = "aliquot_id", values_to = "Status") %>%
  filter(Status != "") %>%         # only keep mutated entries
  mutate(APM_Event = "APM-Mutant") %>% 
  distinct(aliquot_id, .keep_all = T) %>% dplyr::select("aliquot_id", "APM_Event")

HLALOH_pcawg <- fread(".../Project/donors_and_biospecimens/LOH_MSI_final.csv") %>% 
  subset(MSI_mut == "MSS") %>% 
  left_join(., long_df, by = "aliquot_id") %>% 
  mutate(APM_Event = ifelse(!is.na(APM_Event), "APM-Mutant", "APM-WT"),
         APM_Event = factor(APM_Event, levels = c("APM-WT", "APM-Mutant"))) 
table(HLALOH_pcawg$APM_Event)

# pancan_pcawg_2020_clinical_data.tsv was downloaded from the "Clinical Data" page.
TMB_cbio <- fread(".../Project/clinical/pancan_pcawg_2020_clinical_data.tsv") %>% 
  mutate(cibio_perMB = `TMB (nonsynonymous)`,
         cibio_perMB_log = log10(cibio_perMB),
         `icgc_specimen_id` = `Sample ID`)

#LOH_MSIpcawg_check <- inner_join(HLALOH_pcawg, TMB_cbio, by = "icgc_specimen_id")

select_type = c("Breast-AdenoCA", "ColoRect-AdenoCA", "Lymph-BNHL", "Liver-HCC", "Panc-AdenoCA", "Skin-Melanoma")

LOH_MSIpcawg <- HLALOH_pcawg %>%
  filter(MSI_mut == "MSS") %>%
  group_by(histology_abbreviation) %>%
  mutate(distinct_count = n_distinct(APM_Event)) %>%
  filter(distinct_count > 1) %>%
  ungroup() %>%
  left_join(., TMB_cbio, by = "icgc_specimen_id") %>% 
  filter(histology_abbreviation %in% select_type)

y_max <- max(LOH_MSIpcawg$cibio_perMB_log, na.rm = TRUE)

plot_TMB <- ggplot(LOH_MSIpcawg, aes(x = histology_abbreviation, y = cibio_perMB_log, fill = APM_Event)) +
         geom_violin(trim = FALSE, scale = "width", color = NA) +
         scale_fill_manual(values = color_APM_envet) +
         theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 16, colour = "black"),
               axis.text.y = element_text(size = 16, colour = "black"),
               axis.title.y = element_text(size = 16, margin = margin(r = 20)),
         title = element_text(size = 16),
         plot.margin = margin(t = 5, l = 20, r = 20, b = 10),
         legend.text = element_text(size = 10), 
         legend.title = element_text(size = 10),
         legend.key.size = unit(0.5, "cm"), 
         legend.spacing.x = unit(0.2, "cm"),     
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         axis.line = element_line(color = "black"),
         axis.ticks = element_line(color = "black"),
         legend.position = "top") + 
  scale_y_continuous(breaks = log10(c(0.1, 1, 10, 100, 1000, 10000)), 
                     labels = c(0.1, 1, 10, 100, 1000, 10000)) + 
  labs(x = "", y = "TMB", fill = "APM Events") +
  ggtitle("") + 
  stat_compare_means(aes(group = APM_event), method = "wilcox.test", label = "p.signif", size = 7)

ggsave(filename = paste0(path_tmb, "/Figure1c.pdf"), plot = plot_TMB, width = 10, height = 5, units = "in")
```
