---
title: "Figure3C"
author: "AJ"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Load packacges
```{r}
rm(list = ls())

library("stringr")
library("dplyr")
library("patchwork")
library("ggpubr")
library("ggridges")
library("truncnorm")
library("tidyr")
library("scatterpie")
library("tidyselect")
library("pillar")
library("data.table")
library("readr")
library("ggplot2")
library("openxlsx")
library("ggrepel")
library("tibble")
library("textshape")
library("matrixStats")
library("cowplot")
library("ggsci")

## Path
PCAWG_path <- "/Users/wchen20/Desktop/PCAWG"
gritic_path <- paste0(PCAWG_path, "/MHC_evolution/GRITIC/output")

source("/Users/wchen20/Desktop/PCAWG/code/source/basic.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/insert_newlines.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/plot_segTiming.R")

## Timing of segment gain
seg <- fread(paste0(PCAWG_path, "/MHC_evolution/GRITIC/output/SNV_timing/wenjie_posterior_pcawg.tsv"))

## Timing of WGD
wgd_median <- fread("/Users/wchen20/Desktop/PCAWG/MHC_evolution/GRITIC/output/wgd_median.csv") %>% dplyr::select(wgd_mediantiming, sample_id)

## Timing of non-synonymous mutations
nonsyn_filter_nonPloy <- fread("/Users/wchen20/Desktop/PCAWG/MHC_evolution/GRITIC/output/filter/griticnon_filterclonal.tsv") %>%
  dplyr::select(-matches("\\.y$"), -Sample) %>%
  rename_with(~ str_replace_all(., "\\.x$", "")) %>% 
  filter(sample_id %in% sample_MSS)

sample_sucess <- unique(nonsyn_filter_nonPloy$sample_id)
```

# Source
```{r}


```

# Source
```{r}
# *log_odds.tsv: /Users/wchen20/Desktop/2026-02-16_Draft/code/Revision/workflow/4_5_GRITIC_CRCdriver.Rmd
```

# Set Path
```{r}
path_figure <- "/Users/wchen20/Desktop/2026-02-16_Draft/Revision_Figures/Original_output/"
path_figure <- "/Users/wchen20/Desktop/2026-02-16_Draft/Revision_Figures/Original_output/check/"

path_MutationTiming <- "/Users/wchen20/Desktop/2026-02-16_Draft/Final_Results/8_MutationTiming/"
```

## Figure 3C
```{r}
names_new <- c("cohort", "event", "event_split", "type", "perm_run", "log_odds_early", "V1")

file <- paste0(path_MutationTiming, "/timeline/ColoRect-AdenoCA_driver/list_7/list_7.log_odds.tsv")
path_save <- dirname(file)

title="ColoRect-AdenoCA"

boot = basename(file)
boot = sub(".log_odds.tsv", "", boot)
type = sub("_.*$", "", boot)
  
data_sub <- fread(file) %>%
    filter(cohort != "Median")
names(data_sub) <- names_new
data_sub <- data_sub %>% mutate(bootstrap = boot)
  
data <- data_sub %>% 
    mutate(Estimate = type) #%>% 
    #left_join(., prev_df, by = c("cohort", "event"))
  
data$event <- sapply(data$event, insert_newlines_every_five_words)
genes <- unique(data$event)
base_colors <- pal_npg("nrc")(10)
extra_colors <- pal_d3("category20")(20)
color_values <- c(base_colors, extra_colors)[1:length(genes)]
names(color_values) <- genes
  
summary_df <- data %>%
  group_by(event) %>%
  summarise(
    median_beta = median(type, na.rm = TRUE),
    lower95 = quantile(type, 0.025, na.rm = TRUE),
    upper95 = quantile(type, 0.975, na.rm = TRUE),
    mean_log_odds = mean(type, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  ) %>% 
  mutate(
    color_group = case_when(
      lower95 > 0 & upper95 > 0 ~ "Early",
      lower95 < 0 & upper95 < 0 ~ "Late",
      TRUE ~ "Undetermined"),
    Gene = event) %>% 
  arrange(median_beta)
  
  max_value = abs(max(data$type))
  min_value = abs(min(data$type))
  y_lim <- round(max(max_value, min_value)) + 0.05
  
plot_df <- data %>%
  left_join(
    summary_df %>%
      dplyr::select(
        event,
        median_beta,
        lower95,
        upper95,
        color_group
      ),
    by = "event") %>% 
    mutate(Estimate = type,
               Gene = event) 
  
gene_levels <- unique(summary_df$event)
  
plot_df <- plot_df %>%
  mutate(
    Gene = as.character(Gene),
    Gene = factor(Gene, levels = gene_levels),
    gene_id = as.numeric(Gene)
  )
  
  prev_df <- fread(paste0(path_save,"/", boot, ".full_prevalence.tsv"))
  prev_df$event <- sapply(prev_df$event, insert_newlines_every_five_words)
  prev_df <- prev_df %>% mutate(Prevalence = (n_occur / n_samp)*100,
                                event = factor(event, levels = gene_levels))
  type_num <- unique(prev_df$n_samp)
  sampling = sub("^[^_]*_", "", boot)

  if (type %in% c("Eso−AdenoCA", "Lymph−BNHL")) {
    y_label_size = 10
    x_label_size = 10
    bar_size = 3
  } else {
    y_label_size = 14
    x_label_size = 14
    bar_size = 3.5
  }
  ## violin plot
y_lim_high = 0.7
y_lim_low = -0.9

p_violin <- ggplot(
  plot_df,
  aes(
    x = Gene,
    y = Estimate,
    fill = Gene
  )) +
  geom_violin(
    scale = "width",
    trim = TRUE,
    #alpha = 0.7,
    width = 0.6,      
    color = NA,   
  )  +
  geom_boxplot(
    width = 0.1,
    outlier.shape = NA,
    #color = "black",
    alpha = 0.6) +
  theme_cowplot() +
  coord_flip(ylim = c(y_lim_high, y_lim_low)) +
  scale_y_reverse() + 
  scale_fill_manual(values = color_values) +
  ylab("relative log odds timing") +
  xlab(NULL) +
  ggtitle(title) +
  theme(
    axis.text.x = element_text(size = x_label_size, color = "black", hjust = 0.5),
    axis.text.y = element_text(size = y_label_size, color = "black"),
    axis.title.x = element_text(size = 14),
    plot.title = element_text(size = 16, hjust = 0.5, face = "plain"),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.title.y = element_blank(),
    axis.ticks.y = element_line(color = "black"),
    axis.line.y = element_blank(),
    axis.line.x = element_blank(),
    panel.border = element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.7
    ),
    legend.position = "none",
    plot.margin = margin(t = 10, b = 10, l = 10, r = 0)
  )

p_violin

ggsave(filename = paste0(path_figure, "/Figure3C_ColoRect-AdenoCA_.pdf"), plot = p_violin,  width = 4, height = 5.5, units = "in")
```
