---
title: "Figure2A"
author: "AJ"
date: "2025-08-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Libray packages
```{r}
rm(list = ls())

suppressMessages(library("ggplot2"))
suppressMessages(library("patchwork"))
suppressMessages(library("ggpubr"))
suppressMessages(library("maftools"))
suppressMessages(library("survival"))
suppressMessages(library("survminer"))
suppressMessages(library("tidyr"))
suppressMessages(library("broom"))
suppressMessages(library("data.table"))
suppressMessages(library("dplyr"))
suppressMessages(library("ggh4x"))
suppressMessages(library("forcats"))
suppressMessages(library("textshape"))
suppressMessages(library("matrixStats"))
suppressMessages(library("ggrepel"))
suppressMessages(library("tibble"))
suppressMessages(library("readr"))
suppressMessages(library("ggradar"))
suppressMessages(library("ggsci"))
suppressMessages(library("cowplot"))
suppressMessages(library("ggdist"))

PCAWG_path <- "~/Desktop/PCAWG/"

source("~/Desktop/PCAWG/code/source/basic.R")
source("~/Desktop/PCAWG/code/source/EnrichedView_modified.R")
source("~/Desktop/PCAWG/code/source/insert_newlines.R")
source("~/Desktop/PCAWG/code/source/CRP_MAGEMSig0409.R")
```

# Figure 3a
```{r}
cell_types <- c("Tcells", "MHCregulators", "NKcells", "Macrophages", "GammadeltaTcells")
regulators <- c("pos", "neg")

for (cell_type in cell_types) {
  combined_plot <- list()
  for (reg in regulators) {
  
  # Define color based on regulator type
  color <- if (reg == "pos") {
    "#E68674"  # Light blue
  } else if (reg == "neg") {
    "#87AFC6"  # Light red
  }
  
  CRISPR_path <- "~/Desktop/2026-02-16_Draft/Revision/R1Major2/005/"
  
  #CRISPR_pathways <- read.csv(paste0(CRISPR_path, "/Summary/", cell_type, "_C5BP_", reg, "_list.csv"), header = T) 
  Freq_all <- fread(paste0(path_MutationFreq, "/", cell_type, "_Freq_oncoMSS.csv")) %>% 
        filter(percent_mut < 1) %>%
        mutate(pathway_new = sapply(pathway_new, insert_newlines_every_five_words), pathway_new)
    #filter(!histology_abbreviation %in% c("Cervix-AdenoCA", "Bone-Epith", "Breast-LobularCA")) # Cancer type with few samples

  # Select top pathways
  Freq_top <- Freq_all %>% 
  distinct(regulator, pathway, .keep_all = TRUE) %>%
  filter(regulator == reg) %>%
  group_by(regulator) %>%
  slice_max(order_by = percent_whole, n = 8, with_ties = FALSE) %>%
  mutate(Freq_num = percent_whole * nrow(LOH_MSS))

  Pathway_top <- Freq_top %>% pull(pathway)

  # Filter data
  Freq_topcancer <- Freq_all %>%
  filter(pathway %in% Pathway_top, regulator == reg) %>%
  mutate(Freq_num = percent_whole * nrow(LOH_MSS))

  cancer_max <- max(Freq_topcancer$percent_mut) + 0.05
  pan_max <- max(Freq_top$percent_whole) + 0.05
  
  # Identify top labels
  top_labels <- Freq_topcancer %>%
  group_by(pathway_new) %>%
  slice_max(order_by = percent_mut, n = 1) %>%
  ungroup()

  # Colors
  type_colors_named <- setNames(as.character(type_colors), names(type_colors))

  top_labels <- top_labels %>%
    mutate(
    dot_color = type_colors_named[histology_abbreviation],
    histology_factor = factor(histology_abbreviation)
  )

  fill_colors <- setNames(
    type_colors_named[levels(top_labels$histology_factor)],
    levels(top_labels$histology_factor))
  # emove top points from jitter layer
  Freq_no_top <- Freq_topcancer %>%
  anti_join(top_labels, by = c("pathway_new", "histology_abbreviation", "percent_mut"))

  # Plot
  boxplot <- ggplot(Freq_topcancer, aes(x = pathway_new, y = percent_mut)) +
             geom_boxplot(outlier.shape = NA, alpha = 0.9, color = "black", width = 0.5) +
            # Jitter WITHOUT top points
    geom_jitter(
    data = Freq_no_top,
    aes(x = pathway_new, y = percent_mut),
    width = 0.2,
    size = 3,
    alpha = 0.7,
    shape = 21,
    fill = "grey",
    color = "black",
    stroke = 0.1,
    inherit.aes = FALSE
  ) +
  
  # Highlight top point
  geom_point(
    data = top_labels,
    aes(x = pathway_new, y = percent_mut, fill = histology_factor),
    size = 4,
    shape = 21,
    stroke = 0,
    color = "black",
    inherit.aes = FALSE
  ) +
  # Label top point
  geom_text(
    data = top_labels,
    aes(x = pathway_new, y = percent_mut, label = histology_abbreviation),
    hjust = 0.4, vjust = -0.5, size = 4, color = "black",
    inherit.aes = FALSE
  ) +
  scale_fill_manual(values = fill_colors) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(hjust = 1, size = 13, colour = "black"),
    axis.title.y = element_text(size = 13, colour = "black"),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid.major = element_blank(),
    legend.position = "none",
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    plot.margin = margin(t = 20, b = 5, l = 10, r = 5)
  ) +
  labs(y = "Cancer-type Specific", x = "") +
  scale_y_continuous(limits = c(0, cancer_max))
  
  # Create the barplot
  barplot <- ggplot(Freq_top, aes(x = pathway_new, y = percent_whole)) +
    geom_bar(stat = "identity", alpha = 0.9, color = "black", width = 0.5, fill = color) +
    labs(y = "Pan-cancer", x = "") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 30, hjust = 1, size = 14, colour = "black"),
      axis.text.y = element_text(hjust = 1, size = 13, colour = "black"),
      axis.title.y = element_text(size = 13, colour = "black"),
      axis.title.x = element_blank(),
      panel.grid.major = element_blank(),
      legend.position = "none",
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      plot.margin = margin(t = 5, b = 20, l = 20, r = 5)
    ) +
    scale_y_continuous(limits = c(0, pan_max))
  
  combined_plot[[paste0(cell_type, "_", reg)]] <- plot_grid(boxplot, barplot, ncol = 1, align = "v", rel_heights = c(1, 1))
  
  #ggsave(
  #  filename = paste0(path_figure, "/", cell_type, "_", reg, ".pdf"),
  #  plot = combined_plot[[paste0(cell_type, "_", reg)]],
  #  width = 7.5,
  #  height = 6
  #)
  }
  
  #combined_plot <- combined_plot[[1]] + combined_plot[[2]]
  #ggsave(
  #  filename = paste0(path_figure, "/", cell_type, ".pdf"),
  #  plot = combined_plot,
  #  width = 14,
  #  height = 5.5
  #)
  
  combined_plot <- combined_plot[[1]] / combined_plot[[2]]
  ggsave(
    filename = paste0(path_figure, "/", cell_type, "_h.pdf"),
    plot = combined_plot,
    width = 7,
    height = 11
  )
}
```
