---
title: "Figure_V17_Figure4AB"
author: "AJ"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Load Packages
```{r}
rm(list = ls())

library("dndscv")
library("data.table")
library("dplyr")
library("readr")
library("tidyr")
library("stringr")
library("ggplot2")

source("/Users/wchen20/Desktop/PCAWG/code/source/basic.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/plot_dnnsall.R")

PCAWG_path <- "/rsrch6/scratch/hema_bio-Malignan/wchen20/PCAWG"
PCAWG_path <- "/Users/wchen20/Desktop/PCAWG"
figure_path <- "/Users/wchen20/Desktop/PCAWG/Figures/20240827/"

LOH_MSI = LOH_mut <- fread(paste0(PCAWG_path, "/donors_and_biospecimens/LOH_MSI_final.csv"))
LOH_type <- LOH_MSI %>% mutate(sample_id = aliquot_id) %>% dplyr::select(sample_id, histology_abbreviation)
LOH_aliquot <- LOH_MSI %>% mutate(sample_id = aliquot_id) %>% dplyr::select(sample_id, icgc_sample_id, MSI_mut)
LOH_MSS <- LOH_MSI %>% filter(MSI_mut == "MSS")
sample_MSS <- LOH_MSS  %>% pull(aliquot_id)

sample_MSS <- LOH_MSS %>% pull(aliquot_id)
sample_tcgaMSS <- LOH_MSI %>% filter(proj == "tcga", MSI_mut == "MSS") %>% pull(aliquot_id)

rename_list <- fread("/Users/wchen20/Desktop/PCAWG/CRISPR/CRISPRscreen20240118/rename_list.csv")
rename_list$pathway <- str_to_title(rename_list$pathway)

date <- "250807"
dNdScv_dir <- paste0("/Users/wchen20/Desktop/PCAWG/MHC_evolution/DNDS/dNdScv/dNdScvAPM/", date, "/")
dNdScv_input <- "/Users/wchen20/Desktop/PCAWG/MHC_evolution/DNDS/dNdScv/250807/mutations_dNdScv_updated_withsynHLA.txt"
figure_path <- "/Users/wchen20/Desktop/2026-02-16_Draft/Revision_Figures/"
```

## Figure2D
```{r}
dNdScv_plot <- list()
      
width = 6
height = 3.5

cell_types <- c("Tcells", "MHCregulators", "NKcells", "Macrophages", "GammadeltaTcells")

plot_dndsall <- list()
plot_dnds2 <- list()

for (cell_type in cell_types) {
  
  dnds_all <- fread(paste0("/Users/wchen20/Desktop/2026-02-16_Draft/Revision/R2Major3/DNDS/260318/all/with_driver/", cell_type,"/all_", cell_type, ".csv")) %>% 
                    mutate(sig = ifelse((MLE > 0 & upper > 0 & lower > 0) | (MLE < 0 & upper < 0 & lower < 0), "true", "false"))
                    
  dnds_list <- dnds_all %>% filter(sig == "true", name == "wall", MLE > 0) %>% pull(pathway_new) %>% unique()
  #dnds_list <- dnds_all %>% filter(sig == "true", MLE > 0) %>% pull(pathway_new) %>% unique()
  dnds_sig <- dnds_all %>% filter(pathway_new %in% dnds_list)
  
  if (cell_type %in% c("NKcells", "GammadeltaTcells", "MHCregulators")) {
      dnds_sig <- dnds_sig %>% mutate(pathway_new = sapply(pathway_new, insert_newlines_every_five_words2))
    }
  
  plot_dndsall[[cell_type]] <- ggplot(dnds_sig, aes(x = pathway_new, y = MLE, ymax = upper, ymin = lower, group = name, color = name)) +
                      geom_linerange(position = position_dodge(width = 0.5), color = "#A5A4A4") +
                      geom_point(position = position_dodge(width = 0.5), size = 1.5) +
                      geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 0.5) +
                      scale_y_continuous(breaks = log2(c(1, 2, 4, 8, 16)),
                                         labels = function(x) round(2^x, 1)) +
                      scale_color_manual(values = custom_colors, 
                                         labels = custom_labels,
                                         guide = guide_legend(ncol = 1)) +
                      labs(color = "Mutation Type", x = "", y = "DN:DS ratio") +
                      theme(panel.background = element_blank(), 
                            axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1, size = 10, colour = "black"),
                            axis.text.y = element_text(vjust = 0.5, hjust = 1, size = 8, colour = "black"),
                            axis.title.y = element_text(size = 8),
                            legend.text = element_text(size = 6), 
                            legend.title = element_text(size = 7),
                            plot.title = element_text(hjust = 0),
                            panel.grid.major = element_blank(),
                            panel.grid.minor = element_blank(),
                            axis.line = element_line(color = "black"),
                            axis.ticks = element_line(color = "black"),
                            legend.position = "none",
                            legend.key.size = unit(0.8, 'lines'), 
                            plot.margin = unit(c(t = 0, l = 0, r = 0, b = 0), "mm"))
                    
    ggsave(filename =  paste0(figure_path, "/Figure5a_dNdScv_", cell_type,".pdf"), plot = plot_dndsall[[cell_type]], width = 4, height = 2.5, units = "in")
    
    #dnds_path <- paste0(CRISPR_path, "/Summary/dNdScv/", date, "/single/")
    #dnds_single <- fread(paste0(dnds_path, "/dndsall_", cell_type, ".csv")) %>% 
    #mutate(sig = ifelse((MLE > 0 & upper > 0 & lower > 0) | (MLE < 0 & upper < 0 & lower < 0), "true", "false"),
    #       CI = cihigh - cilow)
    
    #dnds_list <- dnds_single %>% filter(sig == "true", MLE > 0) %>% dplyr::select(pathway_new, cancer_type) %>% distinct()
    #dnds_sig <- dnds_single %>% inner_join(dnds_list, by = c("pathway_new", "cancer_type"))
    
    if (cell_type %in% c("Tcells")) {
      nrow = 2
      height = 4
      width = 8
    } else if (cell_type %in% c("MHCregulators")) {
      nrow = 3
      height = 6
      width = 10
      
    } else if (cell_type %in% c("Macrophages")) {
      nrow = 1
      height = 2.5
      width = 6
    } else if (cell_type %in% c("GammadeltaTcells")) {
      nrow = 1
      height = 4
      width = 6
    } else if (cell_type %in% c("NKcells")) {
      nrow = 2
      height = 4
      width = 8
    }
   
    #plot_dnds2[[cell_type]] <- ggplot(dnds_sig, aes(x = cancer_type, y = MLE, ymax = upper, ymin = lower, group = name, color = name)) +
    #  geom_linerange(position = position_dodge(width = 0.5), color = "#A5A4A4") +
    #  geom_point(position = position_dodge(width = 0.5), size = 1.5) +
    #  geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 0.5) +
    #   scale_y_continuous(breaks = pretty(range(dnds_sig$MLE, na.rm = TRUE)),
    #                      labels = function(x) 2^x) +
    #  scale_color_manual(values = custom_colors, labels = custom_labels) +
    #  facet_wrap(~ pathway_new,  scales = "free", nrow = nrow) +
    #  labs(color = "Mutation Type", x = "", y = "DN:DS ratio") +
    #  theme(panel.background = element_blank(), 
    #        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1, size = 8, colour = "black"),
    #        axis.text.y = element_text(vjust = 0.5, hjust = 1, size = 8, colour = "black"),
    #        legend.text = element_text(size = 7, ),  # Adjust legend text size here
    #        legend.title = element_text(size = 7),
    #        plot.title = element_text(hjust = 0),
    #        panel.grid.major = element_blank(),
    #        panel.grid.minor = element_blank(),
    #        axis.line = element_line(color = "black"),
    #        axis.ticks = element_line(color = "black"),
    #        legend.position = "none",
    #        strip.background =element_blank())
    
    #ggsave(filename =  paste0(figure_path, "/SFigure5a_dNdScvsingle_", cell_type ,".pdf"), plot = plot_dnds2[[cell_type]], width = width, height = height, units = "in")
    
}

plot_dndsall_com <- plot_dndsall[[2]] + plot_dndsall[[1]] + plot_dndsall[[4]]
ggsave(filename =  paste0(figure_path, "/Figure5a_dNdScv_com.pdf"), plot = plot_dndsall_com, width = 6, height = 2, units = "in")
```
