---
title: "Spath_figurewaySummary"
author: "AJ"
date: "2026-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Libray packages
```{r}
rm(list = ls())

suppressMessages(library("ggplot2"))
suppressMessages(library("patchwork"))
suppressMessages(library("ggpubr"))
suppressMessages(library("maftools"))
suppressMessages(library("survival"))
suppressMessages(library("survminer"))
suppressMessages(library("tidyr"))
suppressMessages(library("broom"))
suppressMessages(library("data.table"))
suppressMessages(library("dplyr"))
suppressMessages(library("ggh4x"))
suppressMessages(library("forcats"))
suppressMessages(library("textshape"))
suppressMessages(library("matrixStats"))
suppressMessages(library("ggrepel"))
suppressMessages(library("tibble"))
suppressMessages(library("readr"))
suppressMessages(library("ggradar"))
suppressMessages(library("ggsci"))
suppressMessages(library("cowplot"))
suppressMessages(library("ggdist"))

PCAWG_path <- "/Users/wchen20/Desktop/PCAWG/"
gritic_path <- paste0(PCAWG_path, "/MHC_evolution/GRITIC/output")

source("/Users/wchen20/Desktop/PCAWG/code/source/basic.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/EnrichedView_modified.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/insert_newlines.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/CRP_MAGEMSig0409.R")

path_figure <- "/Users/wchen20/Desktop/PCAWG/Figures/20250818/"
```

# Set path
```{r}
path_figure <- "/Users/wchen20/Desktop/2026-02-16_Draft/Revision_Figures/Original_output/"
path_TopHits <- "/Users/wchen20/Desktop/2026-02-16_Draft/Final_Results/5_CRISPR/TopHits/"
```

# SFigure 8
```{r}
cell_type_colors = list("MHCregulators" = "#1E90FF",
                        "Tcells" = "#00CD66",
                        "NKcells"  = "#191970",
                        "Macrophages" = "orange",
                        "GammadeltaTcells" = "#008B8B")


data <- read.xlsx("/Users/wchen20/Desktop/2026-02-16_Draft/Revision/R1Major2/005/overlapped_numer.xlsx") %>%
  mutate(Cell_type = factor(Cell_type, levels = c("MHCregulators", "Tcells", "NKcells", "Macrophages", "GammadeltaTcells")),
         Regulator = factor(Regulator, levels = c("pos", "neg")))

plot_freq <- ggplot(data, aes(x = Regulator, y = Number, fill = Cell_type, alpha = Regulator)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7, color = NA) +
  geom_text(aes(label = Number),
            position = position_dodge(width = 0.8),
            vjust = -0.4, size = 3, alpha = 1) +
  scale_fill_manual(values = cell_type_colors) +
  scale_alpha_manual(values = c(pos = 1, neg = 0.45), guide = "none") +
  facet_wrap(~ Cell_type, nrow = 1, strip.position = "bottom") +
  coord_cartesian(ylim = c(0, 85)) +
  theme_classic() +
  theme(
    axis.text.x      = element_text(size = 10, colour = "black"),
    axis.text.y      = element_text(size = 10, colour = "black"),
    strip.background = element_blank(),
    strip.placement  = "outside",
    strip.text       = element_text(size = 11, face = "plain"),
    legend.position  = "none",
    panel.spacing    = unit(0.5, "lines")
  ) +
  labs(x = NULL, y = "Number")

ggsave(
  filename = paste0(path_figure, "/SFigure8_OverlapFreq.pdf"),
  plot = plot_freq,
  width = 8, height = 3, units = "in")
```

