---
title: "Figure_V17_Figure4AB"
author: "AJ"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Load Packages
```{r}
rm(list = ls())

library("dndscv")
library("data.table")
library("dplyr")
library("readr")
library("tidyr")
library("stringr")
library("ggplot2")

source("/Users/wchen20/Desktop/PCAWG/code/source/basic.R")
source("/Users/wchen20/Desktop/PCAWG/code/source/plot_dnnsall.R")

PCAWG_path <- "/rsrch6/scratch/hema_bio-Malignan/wchen20/PCAWG"
PCAWG_path <- "/Users/wchen20/Desktop/PCAWG"
figure_path <- "/Users/wchen20/Desktop/PCAWG/Figures/20240827/"

LOH_MSI = LOH_mut <- fread(paste0(PCAWG_path, "/donors_and_biospecimens/LOH_MSI_final.csv"))
LOH_type <- LOH_MSI %>% mutate(sample_id = aliquot_id) %>% dplyr::select(sample_id, histology_abbreviation)
LOH_aliquot <- LOH_MSI %>% mutate(sample_id = aliquot_id) %>% dplyr::select(sample_id, icgc_sample_id, MSI_mut)
LOH_MSS <- LOH_MSI %>% filter(MSI_mut == "MSS")
sample_MSS <- LOH_MSS  %>% pull(aliquot_id)

sample_MSS <- LOH_MSS %>% pull(aliquot_id)
sample_tcgaMSS <- LOH_MSI %>% filter(proj == "tcga", MSI_mut == "MSS") %>% pull(aliquot_id)

rename_list <- fread("/Users/wchen20/Desktop/PCAWG/CRISPR/CRISPRscreen20240118/rename_list.csv")
rename_list$pathway <- str_to_title(rename_list$pathway)
```

## SFigure 13
```{r}
## Oncogenic mutations in pathways
col_map <- c(
  "Missense_Mutation" = "#377EB8",
  "Splice_Site"       = "#beaed4",
  "Nonsense_Mutation" = "#4DAF4A",
  "Frame_Shift_Del"   = "#a6d854",
  "Frame_Shift_Ins"   = "#e78ac3",
  "Multi_Hit"         = "#8B2323",
  "In_Frame_Del"      = "#00CD66",
  "In_Frame_Ins"      = "#EEAD0E",
  "Nonstop_Mutation"  = "#fc8d62"
)

df_oncokb_onco <- fread(paste0(path_oncoKB, "/maf_pcawg_oncoKB.maf")) %>% 
    dplyr::filter(ONCOGENIC %in% c("Oncogenic", "Likely Oncogenic")) %>% 
  dplyr::select("Hugo_Symbol", "Chromosome", "Start_Position", "End_Position", "Reference_Allele", "Tumor_Seq_Allele1",
                                      "Tumor_Seq_Allele2", "Tumor_Sample_Barcode", "ONCOGENIC")

df_maf <- fread("/Users/wchen20/Desktop/PCAWG/consensus_snv_indel/non_syn/pcawg_snv_mnv_nonsyn.maf") %>%
  mutate(
    pos_start = as.numeric(gsub(".*?([0-9]+).*", "\\1", HGVSp_Short)),
    pos_end   = as.numeric(gsub(".*_([0-9]+).*", "\\1", HGVSp_Short)),
    pos = ifelse(is.na(pos_end), pos_start, (pos_start + pos_end)/2),
    Tumor_Sample_Barcode = sample_id) %>% 
  left_join(., df_oncokb_onco, by = c("Hugo_Symbol", "Chromosome", "Start_Position", "End_Position", "Reference_Allele", "Tumor_Seq_Allele1",
                                      "Tumor_Seq_Allele2", "Tumor_Sample_Barcode")) %>%
  mutate(onco_mut = ifelse(is.na(ONCOGENIC), "Unknown", "Oncogenic"))

df_impact <- fread("/Users/wchen20/Desktop/PCAWG/consensus_snv_indel/non_syn/mutation_impact/mutation_impact.csv")

cell_types <- c("Tcells", "MHCregulators", "NKcells", "Macrophages", "GammadeltaTcells")
regulators <- c("neg", "pos")
all_plots <- list()
df <- list()
date = "260301"
version = "new"
path_save = "/Users/wchen20/Desktop/2026-02-16_Draft/Revision/R2Major1/Oncogenic/"

for (cell_type in cell_types) {
  
  CRISPR_path <- paste0("/Users/wchen20/Desktop/PCAWG/CRISPR/CRISPRscreen20240118/", cell_type)
  
  for (reg in regulators) {
    
    if (version == "old") {
      
      CRISPR_top10 <- read.csv(paste0(CRISPR_path, "/Summary/", cell_type, "_C5BP_", reg, "_list.csv"), header = T) %>% 
      dplyr::select(Description) %>% pull()
    
     CRISPR_pathways <- fread(paste0(CRISPR_path, "/Summary/", cell_type, "_C5BP_", reg, "_allgenelist.csv")) %>% 
      filter(Pathway1 %in% CRISPR_top10) %>%
      dplyr::select(Gene, Pathway1)
      
    } else if  (version == "new") {
      
      path_validate <- "/Users/wchen20/Desktop/2026-02-16_Draft/Revision/R1Major2/005/Summary/"
           
      CRISPR_pathways <- read.csv(paste0(path_validate, "/", cell_type, "_C5BP_", reg, "_list.csv"), header = T)  %>%
                  separate_rows(geneName, sep = "/") %>% 
                  mutate(Pathway1 = Description, Gene = geneName) %>% 
                  dplyr::select(ID, Description, Gene, Pathway1)
    }
      
    pathway_list <- unique(na.omit(CRISPR_pathways$Pathway1))
    
    for (pathway in pathway_list) {
      
      CRISPR_gene <- CRISPR_pathways %>% filter(Pathway1 == !!pathway) %>% pull(Gene)
      CRISPR_gene <- unique(CRISPR_gene)
      
      pathway = str_to_title(pathway)
      pathway <- gsub("/", "_", pathway)
      title <- paste0(cell_type, "_", reg, "_", pathway)
      
      df_impact_sub <- df_impact %>% filter(Hugo_Symbol %in% CRISPR_gene) 
      write.csv(df_impact_sub, file = paste0(path_save, title, "_all.csv"), row.names = F)
      
      df_impact_sub_onco <- df_impact %>% filter(Hugo_Symbol %in% CRISPR_gene) %>% 
        filter(predict_oncoKB %in% c("Oncogenic", "Likely Oncogenic"))
      write.csv(df_impact_sub_onco, file = paste0(path_save, title, "_onco.csv"), row.names = F)
      
      gene_list <- unique(df_impact_sub_onco$Hugo_Symbol)
      
      for (gene in gene_list) {
        
        # Mutation information
        df_maf_sub <- df_maf %>%
          filter(Hugo_Symbol == !!gene) %>%
          filter(!is.na(pos))
  
        plot_df <- df_maf_sub %>%
          mutate(HGVSp_Short = sub("p.","", HGVSp_Short)) %>%
          group_by(pos, Variant_Classification, Chromosome) %>%
          summarise(count = n(),
              label = paste(unique(HGVSp_Short), collapse = ";"),
              onco_mut = ifelse(any(onco_mut == "Oncogenic"), "Oncogenic", "Other"),
              .groups = "drop")
        
        prop_oncogenic <- plot_df %>%
          summarise(total = n(),
                    oncogenic = sum(onco_mut == "Oncogenic"),
                    proportion = oncogenic / total)
        
        write.csv(prop_oncogenic,
          file = paste0(path_save, "/", title, "_", gene, ".csv"), row.names = FALSE)
        
        chr <- unique(plot_df$Chromosome)[1]
        prot <- maftools::: .getdomains(geneID = gene)
        length <- unique(prot$aa.length)
        
        features <- GRanges(seqnames = paste0("chr", chr),
                            ranges   = IRanges(start = prot$Start, end = prot$End),
                            names    = prot$Label)
        
        names(features) <- features$names
        #features$height <- c(0.05, 0.05)
        
        # Domain colors
        n_feat <- length(features)
        cols <- brewer.pal(max(3, n_feat), "Set3")[1:n_feat]
        mcols(features)$fill <- cols
  
        # ==============================
        # 3. Build GRanges
        # ==============================
        Sample <- GRanges(
        seqnames = paste0("chr", chr),
        ranges   = IRanges(start = round(plot_df$pos), width = 1)
        )

        # ==============================
        # 4. Lollipop height
        # ==============================
        #mcols(Sample)$score <- plot_df$count / max(plot_df$count) * 10
        mcols(Sample)$score <- plot_df$count
  
        # ==============================
        # 5. Colors 
        # ==============================
        # override oncogenic mutations
        base_colors <- col_map[plot_df$Variant_Classification]
        final_colors <- ifelse(
        plot_df$onco_mut == "Oncogenic",
        base_colors,
        "#E0E0E0"
        )

        Sample$color <- final_colors
  
        alpha_vec <- ifelse(
        plot_df$onco_mut == "Oncogenic",
        1,
        0.1)

        Sample$alpha <- alpha_vec

        used_types <- unique(plot_df$Variant_Classification)

        legend <- list(
        labels = used_types,
        col    = col_map[used_types],
        pch    = 16
        )

        names(Sample) <- plot_df$label

        label_vec <- ifelse(
        plot_df$onco_mut == "Oncogenic",
        plot_df$label,
        " ")

        names(Sample) <-label_vec

        pdf(paste0(path_save, "/", "lollipop_trackViewer_", title, "_", gene,".pdf"),
        width = 18, height = 5.5)

        lolliplot(
            Sample,
            features,
            type = "circle",
            ylab = F,
            cex = 0.9,
            jitter = "label",
            label.parameter = list(labels = label_vec),
            dashline.col = "black",
            legend=legend,
            ranges = GRanges(paste0("chr", chr), IRanges(0, length)))
  
          grid.text(gene, x=.1, y=.9, just="top", 
            gp=gpar(cex=2, fontface="bold"))

          dev.off()
          }
    }
  }
}
```