---
title: "Figure_V17_Figure4AB"
author: "AJ"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Load Packages
```{r}
rm(list = ls())

library("dndscv")
library("data.table")
library("dplyr")
library("readr")
library("tidyr")
library("stringr")
library("ggplot2")

PCAWG_path <- "~/Desktop/PCAWG"

source("~/Desktop/PCAWG/code/source/basic.R")
source("~/Desktop/PCAWG/code/source/plot_dnnsall.R")
```

# SFigure 13
## Combine data and make the plot
```{r}
dnds_all <- list()

for (var in c("with_driver", "no_frequentdriver")) {
   
  path_results <- paste0(path_dNdScv, "/all/", var, "/")
  
  file_list <- list.files(path = path_results, pattern = "all_*", recursive = F, full.names = TRUE)
  
  dnds_all[[var]] <- lapply(file_list, fread) %>% rbindlist() %>% mutate(dataset = var)
  
}

dnds_all_combined <- rbindlist(dnds_all)

#NKcells_pos_Signal Transduction By P53 Class Mediator -- BRCA2
#MHCregulators_neg_Carbohydrate Biosynthetic Process -- EP300
#Macrophages_pos_Reg Gr Pathway -- CREBBP
#Macrophages_pos_Hswi Snf Pathway -- ARID1A

plot_dndsall <- list()

for (pathway in c("REG GR Pathway", "SWI SNF Pathway", "Carbohydrate Biosynthetic Process",  "Signal Transduction by P53 Class Mediator")) {
  
  if (pathway == "REG GR Pathway"|pathway =="Protein Destabilization"|pathway =="HATs Acetylate Histones"|pathway =="Activation of Gene Expression by SREBF") {
     gene = "CREBBP"
  } else if (pathway == "SWI SNF Pathway") {
    gene = "ARID1A"
  } else if (pathway == "Signal Transduction by P53 Class Mediator") {
    gene = "BRCA2"
  } else if (pathway == "Carbohydrate Biosynthetic Process") {
    gene = "EP300"
  }
  dnds_all_sub <- dnds_all_combined %>% filter(pathway_new == !!pathway)  %>% 
    mutate(dataset = factor(dataset, levels = c("with_driver", "no_frequentdriver")))
  dnds_all_sub$pathway_new <- sapply(dnds_all_sub$pathway_new, insert_newlines_every_five_words)
  
  dnds_all_sub <- dnds_all_sub %>% filter(Type == "wall")
  
  plot_dndsall[[pathway]] <- ggplot(dnds_all_sub, aes(x = pathway_new, y = MLE, ymax = upper, ymin = lower, group = name, color = name)) +
                      geom_linerange(position = position_dodge(width = 1.2), color = "#A5A4A4") +
                      geom_point(position = position_dodge(width = 0.5), size = 2) +
                      geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 0.5) +
                      scale_y_continuous(breaks = log2(c(1, 2, 4, 8, 16)),
                                         labels = function(x) round(2^x, 1)) +
                      scale_color_manual(values = custom_colors, 
                                         labels = custom_labels,
                                         guide = guide_legend(ncol = 1)) +
                      facet_wrap(~dataset, labeller = as_labeller(c(with_driver = "All Genes", no_frequentdriver = paste0("Excluding ", gene)))) +
                      labs(color = "Mutation Type", x = "", y = "dN:dS ratio", title = pathway) +
                      theme(panel.background = element_blank(), 
                            axis.text.x = element_blank(),
                            axis.ticks.x = element_blank(),
                            axis.text.y = element_text(vjust = 0.5, hjust = 1, size = 8, colour = "black"),
                            axis.title.y = element_text(size = 8),
                            legend.text = element_text(size = 6), 
                            legend.title = element_text(size = 7),
                            plot.title = element_text(hjust = 0, size = 10),
                            panel.grid.major = element_blank(),
                            panel.grid.minor = element_blank(),
                            axis.line = element_line(color = "black"),
                            axis.ticks = element_line(color = "black"),
                            #legend.position = "right",
                            legend.position = "none",
                            legend.key.size = unit(0.8, 'lines'), 
                            plot.margin = unit(c(t = 1, l = 0, r = 0, b = 0), "mm"),
                            strip.text = element_text(size = 8))
}

plot_all <- plot_dndsall[[1]] + plot_dndsall[[2]] + plot_dndsall[[3]] + plot_dndsall[[4]]
ggsave(filename = paste0(path_figure, "/SFigure13_dNdScv_all_only.pdf"), plot = plot_all, width = 6, height = 3.5, units = "in")
```
