---
title: "APM_DNDS"
author: "AJ"
date: "2025-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Load Packages
```{r}
rm(list = ls())

suppressMessages(library("ggplot2"))
suppressMessages(library("patchwork"))
suppressMessages(library("ggpubr"))
suppressMessages(library("maftools"))
suppressMessages(library("survival"))
suppressMessages(library("survminer"))
suppressMessages(library("tidyr"))
suppressMessages(library("broom"))
suppressMessages(library("data.table"))
suppressMessages(library("dplyr"))
suppressMessages(library("forcats"))
suppressMessages(library("textshape"))
suppressMessages(library("ggrepel"))
suppressMessages(library("tibble"))
suppressMessages(library("readr"))
suppressMessages(library("ggradar"))
suppressMessages(library("ggsci"))
suppressMessages(library("cowplot"))
suppressMessages(library("ggdist"))

PCAWG_path <- "~/Desktop/PCAWG/"
source(paste0(PCAWG_path, "/code/source/basic.R"))
source(paste0(PCAWG_path, "/code/source/oncoplot2.R"))
```

# 1. Make plots
```{r}
dnds_all <- fread(paste0(path_dNdScvAPM, "/all.csv"))

dNdScv_plot <- ggplot(dnds_all, aes(x = type, y = MLE, ymax = upper, ymin = lower, group = name, color = name)) +
  geom_linerange(position = position_dodge(width = 0.5), color = "#A5A4A4") +
  geom_point(position = position_dodge(width = 0.5), size = 2) +
  #scale_y_continuous(breaks = c(-4, 0, 4), limits = c(-4.5, 4.5)) +
  scale_y_continuous(breaks = pretty(range(dnds_all$MLE, na.rm = TRUE)),
                          labels = function(x) 2^x) +
  geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 0.8) +
  scale_color_manual(values = custom_colors, labels = custom_labels) +
  labs(color = "Mutation Type", x = "", y = "DN:DS ratio") +
  theme(panel.background = element_blank(), 
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 10, colour = "black"),
        axis.text.y = element_text(vjust = 0.5, hjust = 1, size = 8, colour = "black"),
        axis.title.y = element_text(size = 10), 
        plot.title = element_text(hjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = "black"),
        strip.text = element_text(size = 10),
        legend.title = element_text(size = 8), 
        legend.text = element_text(size = 8))

ggsave(filename = paste0(path_figure, "/SFigure2D.pdf"), plot = dNdScv_plot, width = 10, height = 3, units = "in")
```
