---
title: "Figures_V17_SFigure1BC"
author: "AJ"
date: "2025-08-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Loading Packages
```{r}
rm(list = ls())

suppressMessages(library("ggplot2"))
suppressMessages(library("patchwork"))
suppressMessages(library("ggpubr"))
suppressMessages(library("maftools"))
suppressMessages(library("survival"))
suppressMessages(library("survminer"))
suppressMessages(library("tidyr"))
suppressMessages(library("broom"))
suppressMessages(library("data.table"))
suppressMessages(library("dplyr"))
suppressMessages(library("forcats"))
suppressMessages(library("textshape"))
suppressMessages(library("ggrepel"))
suppressMessages(library("tibble"))
suppressMessages(library("readr"))
suppressMessages(library("ggradar"))
suppressMessages(library("ggsci"))
suppressMessages(library("cowplot"))
suppressMessages(library("ggdist"))

PCAWG_path <- "~/Desktop/PCAWG/"
source(paste0(PCAWG_path, "/code/source/basic.R"))
source(paste0(PCAWG_path, "/code/source/oncoplot2.R"))
```

# 1. Common cancer types
```{r}
mat1 <- fread(paste0(path_APMall, "/onco_APM_hlaloh.txt")) %>% 
  column_to_rownames("V1") %>% 
  as.matrix()

hlaloh <- as.data.frame(mat1) %>%
  rownames_to_column("Gene") %>%
  pivot_longer(-Gene, names_to = "aliquot_id", values_to = "Status") %>%
  filter(Status != "") %>%
  mutate(APM_Event = "APM-Mutant") %>% filter(Gene %in% c("HLALOH")) %>%
  mutate(Gene = "Any",
         HLALOH = "Mutant") %>%
  inner_join(LOH_MSS, ., by = "aliquot_id") %>% filter(aliquot_id %in% sample_MSS)
type_hlaloh <- unique(hlaloh$histology_abbreviation)

long_df <- as.data.frame(mat1) %>%
  rownames_to_column("Gene") %>%
  pivot_longer(-Gene, names_to = "aliquot_id", values_to = "Status") %>%
  filter(Status != "") %>%
  mutate(APM_Event = "APM-Mutant") %>% filter(Gene %in% c("HLA-A", "HLA-B", "HLA-C")) %>%
  distinct(aliquot_id, .keep_all = T) %>% 
  dplyr::select("aliquot_id", "APM_Event")

HLA_mut <- long_df %>% inner_join(LOH_MSS, ., by = "aliquot_id") %>% 
  mutate(HLA_mutation = ifelse(is.na(APM_Event), "WT", "Mutant"),
         count = 1)

type_hlamut <- unique(HLA_mut$histology_abbreviation)
type_all <- c(type_hlaloh, type_hlamut) %>% unique()
```

# SFigure 1b -- Plot for HLA mutations
```{r}
color_event = c("Mutant" = "#E64B35FF", "WT"  = "#4DBBD5FF" )

mat1 <- fread(paste0(path_APMall, "/onco_APM_hlaloh.txt")) %>% 
  column_to_rownames("V1") %>% 
  as.matrix()

long_df <- as.data.frame(mat1) %>%
  rownames_to_column("Gene") %>%
  pivot_longer(-Gene, names_to = "aliquot_id", values_to = "Status") %>%
  filter(Status != "") %>%
  mutate(APM_Event = "APM-Mutant") %>% 
  filter(Gene %in% c("HLA-A", "HLA-B", "HLA-C")) %>%
  distinct(aliquot_id, .keep_all = T) %>% 
  dplyr::select("aliquot_id", "APM_Event")

## SFigure 1b
# HLA point mutations
HLA_mut <- long_df %>% left_join(LOH_MSS, ., by = "aliquot_id") %>% 
  mutate(HLA_mutation = ifelse(is.na(APM_Event), "WT", "Mutant"),
         count = 1)

PCAWG_HLAmut <- HLA_mut %>%
  group_by(histology_abbreviation, HLA_mutation) %>%
  summarise(Total = sum(count)) %>%
  ungroup()

PCAWG_HLAmut_all <- PCAWG_HLAmut %>%
  group_by(histology_abbreviation) %>%
  summarise(Total_all = sum(Total)) %>%
  ungroup() %>%
  left_join(PCAWG_HLAmut, ., by = "histology_abbreviation") %>%
  mutate(Pro = Total/Total_all) %>% 
  mutate(type = paste0(histology_abbreviation, " (n = ", Total_all, ")"),
         HLA_mutation = factor(HLA_mutation, levels = c("WT", "Mutant"))) %>% 
  filter(histology_abbreviation %in% type_all)

HLAmutation_freq <- ggplot(PCAWG_HLAmut_all, aes(x = type, y = Pro, fill = HLA_mutation)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = color_event) +
  labs(title = "HLA SNV/indels", x = "", y = "Proportion", fill = "HLA Mutations") +
  theme_minimal() +
  theme(
    #axis.title.y = element_blank(),
    axis.text.y = element_text(size = 14, color = "black", hjust = 0.5, vjust = 0.5),
    axis.text.x = element_text(size = 14, color = "black", angle = 45, hjust = 1, vjust = 1),
    plot.title = element_text(size = 16),
    axis.title.y = element_text(size = 14),
    plot.margin = margin(0, 5, 5, 15),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    legend.position = "right") +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black", size = 0.5)

ggsave(filename = paste0(path_figure, "/SFigure2b1.pdf"), plot = HLAmutation_freq, width = 10, height = 5, units = "in")
```

# SFigure 1b -- Plot for HLA LOH
```{r}
mat1 <- fread(paste0(path_APMall, "/onco_APM_hlaloh.txt")) %>% 
  column_to_rownames("V1") %>% 
  as.matrix()

hlaloh <- as.data.frame(mat1) %>%
  rownames_to_column("Gene") %>%
  pivot_longer(-Gene, names_to = "aliquot_id", values_to = "Status") %>%
  filter(Status != "") %>%
  mutate(APM_Event = "APM-Mutant") %>% filter(Gene %in% c("HLALOH")) %>%
  mutate(Gene = "Any",
         HLALOH = "Mutant") %>%
  left_join(LOH_MSS, ., by = "aliquot_id") %>%
  mutate(HLA_LOH = ifelse(is.na(HLALOH), "WT", "Mutant")) %>%
  mutate(count = 1) %>% 
  filter(aliquot_id %in% sample_MSS)

table(hlaloh$HLA_LOH)

PCAWG_HLALOH <- hlaloh %>%
  group_by(histology_abbreviation, HLA_LOH) %>%
  summarise(Total = sum(count)) %>%
  ungroup()

PCAWG_LOH <- PCAWG_HLALOH %>%
  group_by(histology_abbreviation) %>%
  summarise(Total_all = sum(Total)) %>%
  ungroup() %>%
  left_join(PCAWG_HLALOH, ., by = "histology_abbreviation") %>%
  mutate(Pro = Total/Total_all) %>% 
  mutate(type = paste0(histology_abbreviation, " (n = ", Total_all, ")"),
         HLA_LOH = factor(HLA_LOH, levels = c("WT", "Mutant")))  %>% 
  filter(histology_abbreviation %in% type_all)

HLALOH_freq <- ggplot(PCAWG_LOH, aes(x = type, y = Pro, fill = HLA_LOH)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = color_event) +
  labs(title = "HLA LOH", x = "", y = "Proportion", fill = "HLA LOH") +
  theme_minimal() +
  theme(
    #axis.title.y = element_blank(),
    axis.text.y = element_text(size = 14, color = "black", hjust = 0.5, vjust = 0.5),
    axis.text.x = element_text(size = 14, color = "black", angle = 45, hjust = 1, vjust = 1),
    plot.title = element_text(size = 16),
    axis.title.y = element_text(size = 14),
    plot.margin = margin(0, 5, 5, 15),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    legend.position = "right") +
    geom_hline(yintercept = 0.5, linetype = "dashed", color = "black", size = 0.5)

HLALOH_freq
ggsave(filename = paste0(path_figure, "/SFigure2b2.pdf"), plot = HLALOH_freq, width = 10, height = 5, units = "in")

# Combine the plots with shared axis
APM_plot <- HLAmutation_freq + HLALOH_freq  + patchwork::plot_layout(nrow = 2)
ggsave(filename = paste0(path_figure, "/SFigure2b.pdf"), plot = APM_plot, width = 15, height = 10, units = "in")
```
